server:
  port: 7001

eureka:
  instance:
    # 单机版
    # hostname: localhost #eureka服务端的实例名称
    # 集群
    hostname: euraka7001.com
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka
